package main.java.enums;

public enum AclEntityTypeEnums {
    PHONEACCESSCONTROLLISTCHECKENTITYTYPE(6),
    EMAILACCESSCONTROLLISTCHECKENTITYTYPE(5),
    PANACCESSCONTROLLISTCHECKENTITYTYPE(2),
    BANKACCOUNTACCESSCONTROLLISTCHECKENTITYTYPE(21),
    BLACKLISTEDCUSTOMERACCESSCONTROLLISTCHECKENTITYTYPE(4),
    OVERLEVERAGEDACUSTOMERACCESSCONTROLLISTCHECKENTITYTYPE(7),
    GEOIPCOUNTRYCHECKENTITYTYPE(0),
    IPACCESSCONTROLLISTCHECKENTITYTYPE(1);

    public final int label;
    private AclEntityTypeEnums(int label) {
        this.label = label;
    }
}
